[package]
name = "scryer-cli-runner"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "scryer-cli-runner"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
strip = true