name: WASI Docker Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        type: choice
        options:
          - release
          - debug
          - dev
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'

env:
  DOCKER_BUILDKIT: 1

jobs:
  docker-build-wasi:
    name: Build WASI via Docker
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="docker-$(echo ${GITHUB_SHA} | cut -c1-8)"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build WASI components with Docker Compose
        run: |
          echo "Building WASI components using Docker..."
          
          # Build the Docker image for WASI compilation
          docker compose build build
          
          # Run the build
          docker compose run --rm build
          
          # Copy artifacts from Docker volumes
          docker compose run --rm build bash -c "
            cp target/scryer-prolog.wasm /workspace/scryer-prolog-cli-docker.wasm &&
            cp target/wasm32-wasip2/wasi-release/scryer_prolog_component.wasm /workspace/scryer-prolog-core-docker.wasm
          "
          
          # Verify the files exist
          ls -lh scryer-prolog-cli-docker.wasm scryer-prolog-core-docker.wasm

      - name: Install wasmtime for testing
        run: |
          curl -sSL https://github.com/bytecodealliance/wasmtime/releases/download/v28.0.0/wasmtime-v28.0.0-x86_64-linux.tar.xz | \
            tar -xJ -C /tmp
          sudo mv /tmp/wasmtime-v28.0.0-x86_64-linux/wasmtime /usr/local/bin/
          wasmtime --version

      - name: Test Docker-built components
        run: |
          echo "Testing Docker-built WASI components..."
          
          # Test basic functionality
          wasmtime run scryer-prolog-cli-docker.wasm -v
          wasmtime run scryer-prolog-cli-docker.wasm -q "X is 5 * 5."
          
          # Quick ISO test
          cat > quick-iso-test.pl << 'EOF'
          test_append :- append([1,2], [3,4], [1,2,3,4]).
          test_member :- member(3, [1,2,3,4]).
          test_arithmetic :- X is 10 + 20, X = 30.
          
          run_tests :-
              (test_append -> write('append: PASS\n') ; write('append: FAIL\n')),
              (test_member -> write('member: PASS\n') ; write('member: FAIL\n')),
              (test_arithmetic -> write('arithmetic: PASS\n') ; write('arithmetic: FAIL\n')).
          EOF
          
          wasmtime run --dir=. scryer-prolog-cli-docker.wasm \
            -f quick-iso-test.pl -q "run_tests."

      - name: Upload Docker-built components
        uses: actions/upload-artifact@v4
        with:
          name: wasi-docker-components-${{ steps.version.outputs.version }}
          path: |
            scryer-prolog-cli-docker.wasm
            scryer-prolog-core-docker.wasm
          retention-days: 30

      - name: Clean up Docker resources
        if: always()
        run: |
          docker compose down -v
          docker system prune -f